### ISSUE TITLE
`tf_lint` toolchain wrapper should support passing options

### ISSUE THREAD

**Issue by wingsofovnia** [yanndegat/rules_tf#8]
There are plenty of options in https://github.com/terraform-linters/tflint that can be passed as tflint arguments, however, due to toolchain providing access not to the binary but a `wrapper.sh`, which is not expecting any args except `{mod_dir} {config_file}`, it is currently not possible to pass additional arguments even with a custom `tf_lint` rule implementation.

I suggest updating `wrapper.sh` to pass extra args (index 3 +) straight to `tflint` binary.

**Comment by yanndegat** [comment]
hi @wingsofovnia thanks for suggestion. if you want to try a PR regarding this extra args, i'd be very pleased.

otherwise i'll try to have a look at it in the following weeks, but i'm pretty busy at this time. so i guess it wont be done in the next couple of weeks.

if it's okay with you,

regards
